// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVaen_JN8hnFLm8mlV9k9BgPydMkOwp_M',
    appId: '1:133334507668:web:80365a758199b879b05481',
    messagingSenderId: '133334507668',
    projectId: 'auth-81909',
    authDomain: 'auth-81909.firebaseapp.com',
    storageBucket: 'auth-81909.appspot.com',
    measurementId: 'G-F7DFN4XV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Ks7HbOx4Lbimk-8isuSJdAXvZJ5ZD0s',
    appId: '1:133334507668:android:d0658156697fe8f8b05481',
    messagingSenderId: '133334507668',
    projectId: 'auth-81909',
    storageBucket: 'auth-81909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwDpm1DgKED72aHP41Pd8TGJ4I1b4FxM',
    appId: '1:133334507668:ios:3763026886600505b05481',
    messagingSenderId: '133334507668',
    projectId: 'auth-81909',
    storageBucket: 'auth-81909.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwDpm1DgKED72aHP41Pd8TGJ4I1b4FxM',
    appId: '1:133334507668:ios:3763026886600505b05481',
    messagingSenderId: '133334507668',
    projectId: 'auth-81909',
    storageBucket: 'auth-81909.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVaen_JN8hnFLm8mlV9k9BgPydMkOwp_M',
    appId: '1:133334507668:web:17ad56f6574383b8b05481',
    messagingSenderId: '133334507668',
    projectId: 'auth-81909',
    authDomain: 'auth-81909.firebaseapp.com',
    storageBucket: 'auth-81909.appspot.com',
    measurementId: 'G-7MRYMH1KQ7',
  );
}
